import { createPrefab, type PrefabRect } from "$lib/algo/VgpExport";
import type { Prefab } from "$lib/data/Vgp";
import type { ColoredRect } from "$lib/algo/Rect";
import type { RectImage } from "$lib/algo/RectImage";
import { Alignment } from "$lib/types/Alignment";
import { unpackColor } from "cardcanvas/color";
import { NativeImage } from "cardcanvas/native-image";
import { calculateRequiredPxPerCu, calculateDimensionPx, encodeCardData } from "cardcanvas/encoding";
import { Canvas } from "cardcanvas/canvas";
import { PrefabType, type GenerationResult } from "$lib/types";
import { determineObjectCount } from "$lib/algo/RectImage";
import type { ExportResult } from "./types/ExportResult";

self.onmessage = async (event: MessageEvent) => {
  const { result, colorIndexMap } = event.data as {
    result: GenerationResult;
    colorIndexMap: Map<number, number>;
  };
  const exportResult = await process(result, colorIndexMap);
  self.postMessage(exportResult);
};

async function process(result: GenerationResult, colorIndexMap: Map<number, number>): Promise<ExportResult> {
  const {
    prefab,
    frames,
    length,
    rects
  } = generatePrefab(result, colorIndexMap);
  
  // vgp export
  const prefabString = JSON.stringify(prefab, (_key, value) => {
    if (typeof value === "number") {
      return Math.round(value * 10000) / 10000;
    }
    return value;
  });
  // card export
  prefab.pa_prefab_png_ver = 1;
  const cardPrefabString = JSON.stringify(prefab, (_key, value) => {
    if (typeof value === "number") {
      return Math.round(value * 10000) / 10000;
    }
    return value;
  });
  const textEncoder = new TextEncoder();
  const uncompressedCardPrefabBuf = textEncoder.encode(cardPrefabString);
  const brotli = await (await import("brotli-wasm")).default;
  const compressedCardPrefabBuf = brotli.compress(uncompressedCardPrefabBuf, {
    quality: 11
  });
  const compressedCardPrefabBase64 = compressedCardPrefabBuf.toBase64();
  const cardDataString = `pa_prefab_br1:${compressedCardPrefabBase64}`;
  const cardData = textEncoder.encode(cardDataString);

  // encode to card
  const pxPerCu = await calculateRequiredPxPerCu(cardData.byteLength);
  const dimensionPx = await calculateDimensionPx(pxPerCu);
  const image = await NativeImage.create(dimensionPx, dimensionPx);
  image.asUint32Array().fill(0xFFFFFFFF); // white background
  
  await encodeCardData(image, pxPerCu, cardData);
  
  // decorate card
  const canvas = await Canvas.create(image);
  canvas.fillRect(14, 14, 228, 26, unpackColor(0xFF000000));
  canvas.fillRect(14, 42, 100, 100, unpackColor(0xFF000000));
  canvas.fillRect(14, 144, 228, 98, unpackColor(0xFF000000));
  drawHeart(canvas, 24, 19);
  canvas.drawText(43, 19, 3, "AFTERBEAT PREFAB", unpackColor(0xFFFFFFFF));
  canvas.drawTextCenterAligned(177, 42, 2, getTypeName(prefab.type ?? 0), unpackColor(0xFF000000));
  canvas.drawText(120, 56, 2, "FRAMES", unpackColor(0xFF000000));
  canvas.drawTextRightAligned(236, 56, 2, frames.toString(), unpackColor(0xFF000000));
  canvas.drawText(120, 69, 2, "LENGTH", unpackColor(0xFF000000));
  canvas.drawTextRightAligned(236, 69, 2, `${Math.round(length * 10) / 10}S`, unpackColor(0xFF000000));
  canvas.drawText(120, 82, 2, "RECTS", unpackColor(0xFF000000));
  canvas.drawTextRightAligned(236, 82, 2, rects.toString(), unpackColor(0xFF000000));
  canvas.drawTextCenterAligned(128, 147, 2, ellipsis(canvas, prefab.n || "untitled", 2, 222), unpackColor(0xFFFFFFFF));
  drawWrappedDescription(canvas, prefab.description || "", 17, 161);
  canvas.drawText(17, 234, 1, "SPARITE.REIMNOP.COM", unpackColor(0xFFFFFFFF));
  canvas.drawTextRightAligned(239, 234, 1, "GENERATED BY CARDCANVAS", unpackColor(0xFFFFFFFF));

  // draw preview
  const scaleFactor = calculateScaleFactor(Math.max(result.rectImage.width, result.rectImage.height), 96 * pxPerCu);
  const preview = await drawImage(result.rectImage, scaleFactor);
  if (preview) {
    const previewImage = await NativeImage.create(preview.width, preview.height);
    previewImage.asUint32Array().set(new Uint32Array(preview.data.buffer));
    const thumbnailX = 16 * pxPerCu + (48 * pxPerCu - preview.width / 2);
    const thumbnailY = 44 * pxPerCu + (48 * pxPerCu - preview.height / 2);
    canvas.drawSubImage(thumbnailX, thumbnailY, previewImage);
  }
  
  // convert to 8-bit RGBA
  const image32Buf = image.asUint32Array();
  const image8Buf = new Uint8ClampedArray(
    image32Buf.buffer.slice(
      image32Buf.byteOffset,
      image32Buf.byteOffset + image32Buf.byteLength
    )
  );

  const exportResult: ExportResult = {
    fileNameWithoutExtension: prefab.n ? normalizeFileName(prefab.n) : "untitled",
    prefabString: prefabString,
    prefabCardWidth: dimensionPx,
    prefabCardHeight: dimensionPx,
    prefabCardImage: image8Buf
  };
  return exportResult;
}

function ellipsis(canvas: Canvas, text: string, size: number, maxWidth: number): string {
  const textWidth = (text: string) => canvas.calculateTextRectSize(text.length, size).width;

  const ellipsis = "...";
  if (textWidth(text) <= maxWidth) return text;
  
  let truncated = text;
  while (truncated.length > 0 && textWidth(truncated + ellipsis) > maxWidth) {
    truncated = truncated.slice(0, -1);
  }
  return truncated + ellipsis;
}

function drawWrappedDescription(canvas: Canvas, description: string, x: number, startY: number) {
  const DESC_MAX_WIDTH = 222;
  const DESC_LINE_HEIGHT = 14;
  const DESC_MAX_LINES = 5;

  const textWidth = (text: string) => canvas.calculateTextRectSize(text.length, 2).width;

  const scale = 2;
  let lines = wrapText(canvas, description, scale, DESC_MAX_WIDTH);

  if (lines.length > DESC_MAX_LINES) {
    lines = lines.slice(0, DESC_MAX_LINES);
    // Apply ellipsis to the last line
    const ellipsisStr = "...";
    let last = lines[DESC_MAX_LINES - 1];
    while (last.length > 0 && textWidth(last + ellipsisStr) > DESC_MAX_WIDTH) {
      last = last.slice(0, -1);
    }
    lines[DESC_MAX_LINES - 1] = last + ellipsisStr;
  }

  lines.forEach((line, i) => {
    canvas.drawText(x, startY + i * DESC_LINE_HEIGHT, scale, line, unpackColor(0xFFFFFFFF));
  });
}

function wrapText(canvas: Canvas, text: string, size: number, maxWidth: number): string[] {
  const textWidth = (text: string) => canvas.calculateTextRectSize(text.length, size).width;

  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (textWidth(candidate) <= maxWidth) {
      current = candidate;
    } else {
      if (current) lines.push(current);
      // Word itself is too wide — hard-break it
      if (textWidth(word) > maxWidth) {
        let chunk = "";
        for (const char of word) {
          if (textWidth(chunk + char) > maxWidth) {
            lines.push(chunk);
            chunk = char;
          } else {
            chunk += char;
          }
        }
        current = chunk;
      } else {
        current = word;
      }
    }
  }
  if (current) lines.push(current);
  return lines;
}

function drawHeart(canvas: Canvas, x: number, y: number) {
  const color = unpackColor(0xFF5254EA);
  const size = 3;
  // row 1
  canvas.fillRect(x + 1 * size, y, size, size, color);
  canvas.fillRect(x + 3 * size, y, size, size, color);
  // row 2, 3
  canvas.fillRect(x, y + 1 * size, 5 * size, 2 * size, color);
  // row 4
  canvas.fillRect(x + 1 * size, y + 3 * size, size * 3, size, color);
  // row 5
  canvas.fillRect(x + 2 * size, y + 4 * size, size, size, color);
}

function generatePrefab(result: GenerationResult, colorIndexMap: Map<number, number>): {
  prefab: Prefab,
  frames: number,
  length: number,
  rects: number
} {
  // allocate prefab rects
  const prefabRects: PrefabRect[] = [];
  const objectCount = determineObjectCount(result.rectImage.frames);
  for (let i = 0; i < objectCount; i++) {
    prefabRects.push({
      positions: [],
      sizes: [],
      colors: []
    });
  }
  
  // loop through every frame
  let time = 0;
  let currentFrameIndex = 0;
  let totalFrames = 0;
  while (time < result.lifetime) {
    const coloredRects = postProcessRectImageFrame(
      result.rectImage,
      currentFrameIndex,
      result.pixelsPerUnit,
      result.horizontalAlignment,
      result.verticalAlignment,
      colorIndexMap
    );

    // push keyframes to prefab rects
    let j = 0;
    for (; j < coloredRects.length; j++) {
      const rect = coloredRects[j];
      prefabRects[j].positions.push({ time, value: [rect.x, rect.y] });
      prefabRects[j].sizes.push({ time, value: [rect.width, rect.height] });
      prefabRects[j].colors.push({ time, value: rect.color });
    }

    // hide remaining objects
    for (; j < prefabRects.length; j++) {
      prefabRects[j].positions.push({ time, value: [0, 0] });
      prefabRects[j].sizes.push({ time, value: [0, 0] });
      prefabRects[j].colors.push({ time, value: { index: 0, opacity: 0 } });
    }

    time += result.rectImage.frames[currentFrameIndex].delay / 1000;
    totalFrames++;

    // advance frame index
    currentFrameIndex++;
    if (currentFrameIndex >= result.rectImage.frames.length) {
      if (!result.looped) {
        break;
      }
      currentFrameIndex = 0;
    }
  }

  const prefab = createPrefab(
    result.prefabName,
    result.prefabDescription,
    result.prefabType,
    result.lifetime,
    result.depth,
    result.useHitObjects,
    prefabRects,
    Date.now()
  );

  return {
    prefab,
    frames: totalFrames,
    length: result.lifetime,
    rects: objectCount
  };
}

function postProcessRectImageFrame(
  rectImage: RectImage,
  frameIndex: number,
  pixelsPerUnit: number,
  horizontalAlignment: Alignment,
  verticalAlignment: Alignment,
  colorMap: Map<number, number>
): ColoredRect[] {
  const scaleFactor = 1 / pixelsPerUnit; // the generator assumes 1 ppu, so scale accordingly
  const offsetX = computeXOffset(rectImage.width * scaleFactor, horizontalAlignment);
  const offsetY = computeYOffset(rectImage.height * scaleFactor, verticalAlignment);
  const frame = rectImage.frames[frameIndex];
  const result = frame.rects.map((rect) => {
    let mappedIndex = colorMap.get(rect.color.index);
    if (mappedIndex === undefined) {
      mappedIndex = rect.color.index;
    }
    return {
      x: rect.x * scaleFactor + offsetX,
      y: rect.y * scaleFactor + offsetY,
      width: rect.width * scaleFactor,
      height: rect.height * scaleFactor,
      color: {
        index: mappedIndex,
        opacity: rect.color.opacity
      }
    };
  });
  return result;
}

function calculateScaleFactor(srcSize: number, dstSize: number) {
  const rawScale = dstSize / srcSize;
  return floorToIntOrInverse(rawScale);
}

function floorToIntOrInverse(x: number): number {
  if (x <= 0)
    throw new Error("x must be positive");

  if (x >= 1) {
    return Math.floor(x);
  } else {
    const m = Math.ceil(1 / x);
    return 1 / m;
  }
}

function drawImage(image: RectImage, scaleFactor: number = 4): { data: Uint8Array, width: number, height: number } | null {
  const canvas = new OffscreenCanvas(image.width * scaleFactor, image.height * scaleFactor);
  const ctx = canvas.getContext("2d");
  if (!ctx)
    return null;

  // clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // disable image smoothing
  ctx.imageSmoothingEnabled = false;

  // draw each rect
  for (const rect of image.frames[0].rects) {
    const x = rect.x * scaleFactor;
    const y = rect.y * scaleFactor;
    const width = rect.width * scaleFactor;
    const height = rect.height * scaleFactor;

    if (width <= 0 || height <= 0) {
      continue;
    }

    const color = image.palette[rect.color.index];
    ctx.fillStyle = `rgba(${color.r}, ${color.g}, ${color.b}, ${rect.color.opacity})`;

    ctx.fillRect(
      x,
      y,
      width,
      height
    );
  }
  
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  return {
    data: new Uint8Array(imageData.data.buffer),
    width: canvas.width,
    height: canvas.height
  };
}

function computeXOffset(width: number, horizontalAlignment: Alignment) {
  if (horizontalAlignment === Alignment.Left) {
    return 0;
  }
  if (horizontalAlignment === Alignment.Center) {
    return -width / 2;
  }
  return -width;
}

function computeYOffset(height: number, verticalAlignment: Alignment) {
  if (verticalAlignment === Alignment.Top) {
    return 0;
  }
  if (verticalAlignment === Alignment.Middle) {
    return -height / 2;
  }
  return -height;
}

function getTypeName(type: PrefabType): string {
  switch (type) {
    case PrefabType.Character:
      return "Character";
    case PrefabType.CharacterParts:
      return "Char Parts";
    case PrefabType.Props:
      return "Props";
    case PrefabType.Bullets:
      return "Bullets";
    case PrefabType.Pulses:
      return "Pulses";
    case PrefabType.Bombs:
      return "Bombs";
    case PrefabType.Spinners:
      return "Spinners";
    case PrefabType.Beams:
      return "Beams";
    case PrefabType.Static:
      return "Static";
    case PrefabType.Misc1:
      return "Misc 1";
    case PrefabType.Misc2:
      return "Misc 2";
    case PrefabType.Misc3:
      return "Misc 3";
    default:
      return "Unknown";
  }
}

function normalizeFileName(name: string): string {
  // convert all non-alphanumeric characters to underscores
  return name.replace(/[^a-zA-Z0-9]/gi, "_").toLowerCase();
}

export {};
